# Generated by Django 4.2.6 on 2023-11-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_visit_description_visit_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
