# Generated by Django 4.2.6 on 2023-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_visit_end_date_alter_visit_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
